#Game configuration
music_volume: 5

# --------------- DO NOT CHANGE THE FOLLOWING CONFIGURATION ---------------

# Path
base_path: /var/jazz/client_src

# Resources folder
resources_path: /var/jazz/client_src/resources
background_path: /var/jazz/client_src/resources/backgrounds
characters_path: /var/jazz/client_src/resources/characters
enemies_path: /var/jazz/client_src/resources/enemies
fonts_path: /var/jazz/client_src/resources/fonts
maps_textures_path: /var/jazz/client_src/resources/maps

projectiles_path: /var/jazz/client_src/resources/projectiles
sounds_path: /var/jazz/client_src/resources/sounds
tiles_path: /var/jazz/client_src/resources/tiles
items_path: /var/jazz/client_src/resources/items

# Animations folder
animations_path: /var/jazz/client_src/animations
ammo_animations_path: /var/jazz/client_src/animations/ammo
projectiles_animations_path: /var/jazz/client_src/animations/projectiles
valuables_animations_path: /var/jazz/client_src/animations/valuables

# External folder
maps_path: /var/jazz/external/maps